routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

//Route::redirect('/', 'dashboard');
Auth::routes(['register' => false]);
Route::group(['middleware' => 'admin'], function () {

    Auth::routes();
    Route::get('/', function () {
        return redirect('/admin/dashboard');
    });
    Route::get('/payment', 'Auth\LoginController@payment');

    Route::get('/login', 'Auth\LoginController@login')->name('login');
    Route::post('/login', 'Auth\LoginController@checklogin')->name('login');

    Route::group(['middleware' => ['auth', 'isAdmin'], 'as' => 'admin.', 'namespace' => 'Admin'], function () {
        Route::post('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');


        Route::post('ckeditor/image_upload', 'HomeController@upload')->name('upload');

        Route::redirect('/', function () {
            echo "here";
        });
        Route::get('/dashboard', 'DashBoardController@dashboard')->name('dashboard');

        //Role resource
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionsController');


        //Language resource
        Route::post('languages/switchUpdate', 'LanguagesController@switchUpdate')->name('languages.switchUpdate');
        Route::resource('languages', 'LanguagesController');
        Route::delete('languages_mass_destroy', 'LanguagesController@massDestroy')->name('languages.mass_destroy');

        //User Type resource
        Route::post('users/switchUpdate', 'UserController@switchUpdate')->name('users.switchUpdate');
        Route::resource('users', 'UserController');
        Route::delete('users_mass_destroy', 'UserController@massDestroy')->name('users.mass_destroy');
        Route::get('unableDeleteUser', 'UserController@unableDeleteUser')->name('users.unableDeleteUser');
        Route::post('users/document/view', 'UserController@usersDocumentView')->name('users.document.view');
        Route::post('users/document/save', 'UserController@usersDocumentSave')->name('users.document.save');
        Route::get('users/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('users.document.verify');
        Route::post('users/document/verify/save', 'UserController@usersDocumentVerifySave')->name('users.document.verify.save');


        Route::get('users/order/show/{id?}', 'UserController@usersOrderShow')->name('users.order.show');
        Route::get('vendors/order/show/{id?}', 'UserController@vendorsOrderShow')->name('vendors.order.show');
        Route::get('drivers/order/show/{id?}', 'UserController@driversOrderShow')->name('drivers.order.show');


        //Vendor Type resource
        Route::post('vendors/switchUpdate', 'VendorController@switchUpdate')->name('vendors.switchUpdate');
        Route::resource('vendors', 'VendorController');
        Route::delete('vendors_mass_destroy', 'VendorController@massDestroy')->name('vendors.mass_destroy');
        Route::post('vendorProduct/onOff', 'VendorController@productOnOff')->name('vendors.product.onOff');
        Route::post('vendors/document/view', 'UserController@usersDocumentView')->name('vendors.document.view');
        Route::post('vendors/document/save', 'UserController@usersDocumentSave')->name('vendors.document.save');
        Route::get('vendors/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('vendors.document.verify');
        Route::post('vendors/document/verify/save', 'UserController@usersDocumentVerifySave')->name('vendors.document.verify.save');
        Route::post('vendors/product/status', 'VendorController@productStatus')->name('vendors.product.status');


        //Driver Type resource
        Route::post('drivers/switchUpdate', 'DriverController@switchUpdate')->name('drivers.switchUpdate');
        Route::resource('drivers', 'DriverController');
        Route::delete('drivers_mass_destroy', 'DriverController@massDestroy')->name('drivers.mass_destroy');
        Route::post('drivers/document/view', 'UserController@usersDocumentView')->name('drivers.document.view');
        Route::post('drivers/document/save', 'UserController@usersDocumentSave')->name('drivers.document.save');
        Route::get('drivers/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('drivers.document.verify');
        Route::post('drivers/document/verify/save', 'UserController@usersDocumentVerifySave')->name('drivers.document.verify.save');

        //Keyword resource
        Route::post('keyword/keywordUpdate', 'KeywordController@switchUpdate')->name('keyword.switchUpdate');
        Route::resource('keyword', 'KeywordController');
        Route::delete('keyword', 'KeywordController@massDestroy')->name('keyword.mass_destroy');

        //Keyword resource
        Route::post('keywords/switchUpdate', 'KeywordController@switchUpdate')->name('keywords.switchUpdate');
        Route::resource('keywords', 'KeywordController');
        Route::delete('keywords', 'KeywordController@massDestroy')->name('keywords.mass_destroy');

        //Category Type resource
        Route::post('categories/switchUpdate', 'CategoryController@switchUpdate')->name('categories.switchUpdate');
        Route::resource('categories', 'CategoryController');
        Route::delete('categories_mass_destroy', 'CategoryController@massDestroy')->name('categories.mass_destroy');

        //Service Type resource
        Route::post('services/switchUpdate', 'ServiceTypeController@switchUpdate')->name('services.switchUpdate');
        Route::resource('services', 'ServiceTypeController');
        Route::delete('services_mass_destroy', 'ServiceTypeController@massDestroy')->name('services.mass_destroy');

        //Business Type resource
        Route::post('businesses/switchUpdate', 'BusinessTypeController@switchUpdate')->name('businesses.switchUpdate');
        Route::resource('businesses', 'BusinessTypeController');
        Route::delete('businesses_mass_destroy', 'BusinessTypeController@massDestroy')->name('businesses.mass_destroy');

        //Unit Type resource
        Route::post('units/switchUpdate', 'UnitTypeController@switchUpdate')->name('units.switchUpdate');
        Route::resource('units', 'UnitTypeController');
        Route::delete('units_mass_destroy', 'UnitTypeController@massDestroy')->name('units.mass_destroy');

        //Order Status resource
        Route::post('orderStatuses/switchUpdate', 'OrderStatusController@switchUpdate')->name('orderStatuses.switchUpdate');
        Route::resource('orderStatuses', 'OrderStatusController');
        Route::delete('orderStatuses_mass_destroy', 'OrderStatusController@massDestroy')->name('orderStatuses.mass_destroy');

        Route::resource('settings', 'SettingController');

        //Vehicle Type resource
        Route::post('vehicletypes/switchUpdate', 'VehicleTypeController@switchUpdate')->name('vehicletypes.switchUpdate');
        Route::resource('vehicletypes', 'VehicleTypeController');
        Route::delete('vehicletypes_mass_destroy', 'VehicleTypeController@massDestroy')->name('vehicletypes.mass_destroy');

        //Vehicle Color resource
        Route::post('vehiclecolors/switchUpdate', 'VehicleColorController@switchUpdate')->name('vehiclecolors.switchUpdate');
        Route::resource('vehiclecolors', 'VehicleColorController');
        Route::delete('vehiclecolors_mass_destroy', 'VehicleColorController@massDestroy')->name('vehiclecolors.mass_destroy');

        //promocodes resource
        Route::post('promocodes/switchUpdate', 'PromocodeController@switchUpdate')->name('promocodes.switchUpdate');
        Route::resource('promocodes', 'PromocodeController');
        Route::delete('promocodes_mass_destroy', 'PromocodeController@massDestroy')->name('promocodes.mass_destroy');

        //promotions resource
        Route::post('promotions/switchUpdate', 'PromotionController@switchUpdate')->name('promotions.switchUpdate');
        Route::resource('promotions', 'PromotionController');
        Route::delete('promotions_mass_destroy', 'PromotionController@massDestroy')->name('promotions.mass_destroy');

        //promotions resource
        Route::post('contents/switchUpdate', 'ContentController@switchUpdate')->name('content.switchUpdate');
        Route::resource('/content', 'ContentController');
        Route::delete('contents', 'ContentController@massDestroy')->name('content.mass_destroy');

        //promotions resource
        Route::post('cashoutrequest/switchUpdate', 'CashoutRequestController@switchUpdate')->name('cashoutrequest.switchUpdate');
        Route::resource('/cashoutrequest', 'CashoutRequestController');
        Route::delete('cashoutrequest', 'CashoutRequestController@massDestroy')->name('cashoutrequest.mass_destroy');

        //document resource
        Route::post('documents/switchUpdate', 'DocumentsController@switchUpdate')->name('documents.switchUpdate');
        Route::resource('/documents', 'DocumentsController');
        Route::delete('documents', 'DocumentsController@massDestroy')->name('documents.mass_destroy');

        //cbd and cannabis resource
        Route::post('cbdcannabistates/switchUpdate', 'CbdCannabiStateController@switchUpdate')->name('cbdcannabistates.switchUpdate');
        Route::resource('/cbdcannabistates', 'CbdCannabiStateController');
        Route::delete('cbdcannabistates', 'CbdCannabiStateController@massDestroy')->name('cbdcannabistates.mass_destroy');


        //currency
        Route::post('currencys/switchUpdate', 'CurrencysController@switchUpdate')->name('currencys.switchUpdate');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
// });

//Route::redirect('/', 'dashboard');
Route::get('/', function(){ echo "user";});
Route::group(['as' => 'user.', 'namespace' => 'User'], function () {
    Route::get('/login', );
});

resources/views/admin/document-approval.blade.php
@extends('layouts.admin')

@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")

        <div class="col-xl-12">
            <div class="row">
                <h2>{{$doc_name}}</h2>
                <img src="{{ asset(Storage::url($doc_image))}}" alt="document_image" class="" style="height: auto;width:100%;">
                <form method="POST" action="{{ route('admin.users.document.save')}}">
                    @csrf
                    <input type="hidden" name="doc_type" value="{{$doc_type}}"/>
                    <input type="hidden" name="user_id" value="{{$user_id}}"/>
                    <button  type="submit" class="btn btn-success btn-lg mt-3">Approved</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection            

resources/views/admin/orders.blade.php
@extends('layouts.admin')
@section('content')
<style>
    .datatable-User1 .order_status .badge{
        font-size: 100% !important;
        min-width: 110px !important;
    }
</style>
    <div class="page-content">
        <div class="container-fluid">
            @include('partials.alert')
            <div class="row">
                <div class="col-lg-3">
                    All Orders
                </div>
                <div class="col-lg-9 mb-3 text-right">
                    {{-- <a class="btn btn-primary" href="{{ route('admin.vendors.index') }}">
                        {{ trans('global.back_to_list') }}
                    </a> --}}
                    <div class="btn-group submitter-group float-right">
                        <div class="input-group-prepend">
                            <div class="input-group-text">Status</div>
                        </div>
                        <select class="form-control status-dropdown">
                            <option value="">All</option>
                        @foreach($orders_status as $value)
                            <option value="{{$value->id}}">{{$value->order_status_name->value}}</option>
                        @endforeach
                        </select>
                    </div>    
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-User1"
                            style="width:100%">
                            <thead>
                                <tr>
                                    <th>
                                        {{ trans('global.no') }}
                                    </th>
                                    <th>
                                        Order ID
                                    </th>
                                    <th>
                                        Transaction ID
                                    </th>
                                    <th>
                                        Customer Name
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.store_name') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.store_contact') }}
                                    </th>
                                   
                                   
                                    <th>
                                        {{ trans('cruds.user-order.driver_name') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.driver_contact') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.order_amount') }}
                                    </th>
                                    <th>
                                        Vendor Earned
                                    </th>
                                    <th>
                                        Driver Earned
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.home_delivery') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.status') }}
                                    </th>
                                    <th>
                                        Cancel Reason
                                    </th>
                                    <th>
                                        Created_At
                                    </th>
                                    <th>
                                        Updated_At
                                    </th>
                                    <th>
                                        {{ trans('cruds.user-order.action') }}
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $badge_array = ['','success', 'secondary', 'danger', 'warning', 'info', 'light', 'dark', 'primary','success']; ?>
                                @foreach ($orders as $key => $order)
                                    <tr data-entry-id="{{ $order->id ?? '' }}">
                                        <td>
                                            {{ $key + 1 ?? '' }}
                                        </td>
                                        <td>
                                            <a href="{{ route('admin.vendors.order.show', ['id' => $order->id]) }}">
                                                {{ $order->id ?? '' }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $order->transaction_number ?? '' }}
                                        </td>
                                        <td>
                                            @if (isset($order->order_user))
                                                <a href="{{ route('admin.users.show', $order->order_user->id) }}">
                                                    {{ $order->order_user ? $order->order_user->first_name.' '.$order->order_user->last_name :  '-' }}
                                                </a>
                                            @else
                                                -    
                                            @endif
                                        </td>
                                        <td>
                                            @if (isset($order->order_vendor))
                                                <a href="{{ route('admin.vendors.show', $order->order_vendor->id) }}">
                                                    {{ $order->order_vendor->store_name ?? '-' }}
                                                </a>
                                            @else
                                                -    
                                            @endif
                                        </td>
                                        <td>
                                            @if (isset($order->order_vendor))
                                                <a href="{{ route('admin.vendors.show', $order->order_vendor->id) }}">
                                                    {{ $order->order_vendor->store_country_code ? (strpos($order->order_vendor->store_country_code, '+') !== false ? '(' . $order->order_vendor->store_country_code . ')' : '(+' . $order->order_vendor->store_country_code . ')') : '' }}
                                                    {{ $order->order_vendor->store_contact ?? '' }}
                                                </a>
                                            @else
                                                -     
                                            @endif
                                        </td>
                                       
                                       
                                        <td>
                                            @if (isset($order->order_driver))
                                                <a href="{{ route('admin.drivers.show', $order->order_driver->id) }}">
                                                    {{ $order->order_driver->first_name ?? '-' }}

                                                </a>
                                            @else
                                                -     
                                            @endif
                                        </td>
                                        <td>
                                            @if (isset($order->order_driver))
                                                <a href="{{ route('admin.drivers.show', $order->order_driver->id) }}">
                                                    {{ $order->order_driver->country_code ? (strpos($order->order_driver->country_code, '+') !== false ? '(' . $order->order_driver->country_code . ')' : '(+' . $order->order_driver->country_code . ')') : '' }}
                                                    {{ $order->order_driver->mobile_no ?? '' }}

                                                </a>
                                            @else
                                                -     
                                            @endif
                                        </td>
                                        <td>
                                            {{ $order->total ?? '' }}
                                        </td>
                                        <?php 
                                            $vendor_wallet='-';
                                            $driver_wallet='-';
                                            if($order->order_status_id == 5 || $order->order_status_id == 9){
                                                $vendor_wallet=$order->vendor_wallet;
                                                $driver_wallet=$order->driver_wallet;
                                            }
                                        ?>
                                        <td>
                                            {{ $vendor_wallet }}
                                        </td>
                                        <td>
                                            {{ $driver_wallet  }}
                                        </td>
                                        <td>
                                            @if ($order->is_pickup == 0)
                                                <span class="badge badge-success">Yes</span>
                                            @else
                                                <span class="badge badge-info">No</span>
                                            @endif
                                        </td>
                                        <td class="order_status">
                                            <span style="display: none;">{{ $order->order_status_id}}</span>
                                            <span class="badge badge-<?php if (isset($badge_array[$order->order_status_id])) {
                                                echo $badge_array[$order->order_status_id];
                                            } else {
                                                echo 'primary';
                                            } ?>">
                                                {{ ($order->order_status && $order->order_status->order_status_name) ? $order->order_status->order_status_name->value : '' }}
                                            </span>
                                            
                                        </td>
                                        <td>
                                            {{ $order->cancel_reason ?? '-' }}
                                        </td>
                                        <td>
                                            {{ $order->created_at ? date('d-M-Y  h:i:s', strtotime($order->created_at)) : '' }}
                                        </td>
                                        <td>
                                            {{ $order->updated_at ? date('d-M-Y  h:i:s', strtotime($order->updated_at)) : '' }}
                                        </td>
                                        <td>

                                            <a href="{{ route('admin.vendors.order.show', ['id' => $order->id]) }}"
                                                title="Show" class="btn btn-sm btn-success">
                                                <i class="fa fa-eye font-size-18"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(function() {
            var table = $('.datatable-User1').DataTable();
            //datatable start index is Zero
            var status = "<?php echo $select_status;?>";
            if(status != null && status != ""){
                table.columns(12).search(status).draw(); 
                $(".status-dropdown option[value="+status+"]").attr('selected', 'selected');
            }
            
            $('.status-dropdown').on('change', function(e){
                var status = $(this).val();
                $('.status-dropdown').val(status)
                table.column(12).search(status).draw();
            })
        });
    </script>
@endsection