routes/admin.php
        Route::resource('permissions', 'PermissionsController');


        //Language resource
        Route::post('languages/switchUpdate', 'LanguagesController@switchUpdate')->name('languages.switchUpdate');
        Route::resource('languages', 'LanguagesController');
        Route::delete('languages_mass_destroy', 'LanguagesController@massDestroy')->name('languages.mass_destroy');

        //User Type resource
        Route::post('users/switchUpdate', 'UserController@switchUpdate')->name('users.switchUpdate');
        Route::resource('users', 'UserController');
        Route::delete('users_mass_destroy', 'UserController@massDestroy')->name('users.mass_destroy');
        Route::get('unableDeleteUser', 'UserController@unableDeleteUser')->name('users.unableDeleteUser');
        Route::post('users/document/view', 'UserController@usersDocumentView')->name('users.document.view');
        Route::post('users/document/save', 'UserController@usersDocumentSave')->name('users.document.save');
        Route::get('users/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('users.document.verify');
        Route::post('users/document/verify/save', 'UserController@usersDocumentVerifySave')->name('users.document.verify.save');


        Route::get('users/order/show/{id?}', 'UserController@usersOrderShow')->name('users.order.show');
        Route::get('vendors/order/show/{id?}', 'UserController@vendorsOrderShow')->name('vendors.order.show');
        Route::get('drivers/order/show/{id?}', 'UserController@driversOrderShow')->name('drivers.order.show');


        //Vendor Type resource
        Route::post('vendors/switchUpdate', 'VendorController@switchUpdate')->name('vendors.switchUpdate');
        Route::resource('vendors', 'VendorController');
        Route::delete('vendors_mass_destroy', 'VendorController@massDestroy')->name('vendors.mass_destroy');
        Route::post('vendorProduct/onOff', 'VendorController@productOnOff')->name('vendors.product.onOff');
        Route::post('vendors/document/view', 'UserController@usersDocumentView')->name('vendors.document.view');
        Route::post('vendors/document/save', 'UserController@usersDocumentSave')->name('vendors.document.save');
        Route::get('vendors/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('vendors.document.verify');
        Route::post('vendors/document/verify/save', 'UserController@usersDocumentVerifySave')->name('vendors.document.verify.save');
        Route::post('vendors/product/status', 'VendorController@productStatus')->name('vendors.product.status');


        //Driver Type resource
        Route::post('drivers/switchUpdate', 'DriverController@switchUpdate')->name('drivers.switchUpdate');
        Route::resource('drivers', 'DriverController');
        Route::delete('drivers_mass_destroy', 'DriverController@massDestroy')->name('drivers.mass_destroy');
        Route::post('drivers/document/view', 'UserController@usersDocumentView')->name('drivers.document.view');
        Route::post('drivers/document/save', 'UserController@usersDocumentSave')->name('drivers.document.save');
        Route::get('drivers/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('drivers.document.verify');
        Route::post('drivers/document/verify/save', 'UserController@usersDocumentVerifySave')->name('drivers.document.verify.save');

        //Keyword resource
        Route::post('keyword/keywordUpdate', 'KeywordController@switchUpdate')->name('keyword.switchUpdate');
        Route::resource('keyword', 'KeywordController');
        Route::delete('keyword', 'KeywordController@massDestroy')->name('keyword.mass_destroy');

        //Keyword resource
        Route::post('keywords/switchUpdate', 'KeywordController@switchUpdate')->name('keywords.switchUpdate');
        Route::resource('keywords', 'KeywordController');
        Route::delete('keywords', 'KeywordController@massDestroy')->name('keywords.mass_destroy');

        //Category Type resource
        Route::post('categories/switchUpdate', 'CategoryController@switchUpdate')->name('categories.switchUpdate');
        Route::resource('categories', 'CategoryController');
        Route::delete('categories_mass_destroy', 'CategoryController@massDestroy')->name('categories.mass_destroy');

        //Service Type resource
        Route::post('services/switchUpdate', 'ServiceTypeController@switchUpdate')->name('services.switchUpdate');
        Route::resource('services', 'ServiceTypeController');
        Route::delete('services_mass_destroy', 'ServiceTypeController@massDestroy')->name('services.mass_destroy');

        //Business Type resource
        Route::post('businesses/switchUpdate', 'BusinessTypeController@switchUpdate')->name('businesses.switchUpdate');
        Route::resource('businesses', 'BusinessTypeController');
        Route::delete('businesses_mass_destroy', 'BusinessTypeController@massDestroy')->name('businesses.mass_destroy');

        //Unit Type resource
        Route::post('units/switchUpdate', 'UnitTypeController@switchUpdate')->name('units.switchUpdate');
        Route::resource('units', 'UnitTypeController');
        Route::delete('units_mass_destroy', 'UnitTypeController@massDestroy')->name('units.mass_destroy');

        //Order Status resource
        Route::post('orderStatuses/switchUpdate', 'OrderStatusController@switchUpdate')->name('orderStatuses.switchUpdate');
        Route::resource('orderStatuses', 'OrderStatusController');
        Route::delete('orderStatuses_mass_destroy', 'OrderStatusController@massDestroy')->name('orderStatuses.mass_destroy');

        Route::resource('settings', 'SettingController');

        //Vehicle Type resource
        Route::post('vehicletypes/switchUpdate', 'VehicleTypeController@switchUpdate')->name('vehicletypes.switchUpdate');
        Route::resource('vehicletypes', 'VehicleTypeController');
        Route::delete('vehicletypes_mass_destroy', 'VehicleTypeController@massDestroy')->name('vehicletypes.mass_destroy');

        //Vehicle Color resource
        Route::post('vehiclecolors/switchUpdate', 'VehicleColorController@switchUpdate')->name('vehiclecolors.switchUpdate');
        Route::resource('vehiclecolors', 'VehicleColorController');
        Route::delete('vehiclecolors_mass_destroy', 'VehicleColorController@massDestroy')->name('vehiclecolors.mass_destroy');

        //promocodes resource
        Route::post('promocodes/switchUpdate', 'PromocodeController@switchUpdate')->name('promocodes.switchUpdate');
        Route::resource('promocodes', 'PromocodeController');
        Route::delete('promocodes_mass_destroy', 'PromocodeController@massDestroy')->name('promocodes.mass_destroy');

        //promotions resource
        Route::post('promotions/switchUpdate', 'PromotionController@switchUpdate')->name('promotions.switchUpdate');
        Route::resource('promotions', 'PromotionController');
        Route::delete('promotions_mass_destroy', 'PromotionController@massDestroy')->name('promotions.mass_destroy');

        //promotions resource
        Route::post('contents/switchUpdate', 'ContentController@switchUpdate')->name('content.switchUpdate');
        Route::resource('/content', 'ContentController');
        Route::delete('contents', 'ContentController@massDestroy')->name('content.mass_destroy');

        //promotions resource
        Route::post('cashoutrequest/switchUpdate', 'CashoutRequestController@switchUpdate')->name('cashoutrequest.switchUpdate');
        Route::resource('/cashoutrequest', 'CashoutRequestController');
        Route::delete('cashoutrequest', 'CashoutRequestController@massDestroy')->name('cashoutrequest.mass_destroy');

        //document resource
        Route::post('documents/switchUpdate', 'DocumentsController@switchUpdate')->name('documents.switchUpdate');
        Route::resource('/documents', 'DocumentsController');
        Route::delete('documents', 'DocumentsController@massDestroy')->name('documents.mass_destroy');

        //cbd and cannabis resource
        Route::post('cbdcannabistates/switchUpdate', 'CbdCannabiStateController@switchUpdate')->name('cbdcannabistates.switchUpdate');
        Route::resource('/cbdcannabistates', 'CbdCannabiStateController');
        Route::delete('cbdcannabistates', 'CbdCannabiStateController@massDestroy')->name('cbdcannabistates.mass_destroy');


        //currency
        Route::post('currencys/switchUpdate', 'CurrencysController@switchUpdate')->name('currencys.switchUpdate');
        Route::resource('/currencys', 'CurrencysController');
        Route::delete('currencys', 'CurrencysController@massDestroy')->name('currencys.mass_destroy');

        Route::get('orders/{status?}', 'UserController@Allorders')->name('orders');
        Route::post('orders/change/status', 'UserController@adminOrderChangeStatus')->name('order.change.status');
        Route::post('orders/change/reverse/entry', 'UserController@adminOrderReverseEntry')->name('order.change.reverse.entry');
    
        //strain effects resource
        Route::post('strain-effects/switchUpdate', 'StrainEffectController@switchUpdate')->name('strain-effects.switchUpdate');
        Route::resource('/strain-effects', 'StrainEffectController');
        Route::delete('strain-effects', 'StrainEffectController@massDestroy')->name('strain-effects.mass_destroy');

         //strain effects resource
         Route::post('cashout-types/switchUpdate', 'CashoutTypeController@switchUpdate')->name('cashout-types.switchUpdate');
         Route::resource('/cashout-types', 'CashoutTypeController');
         Route::delete('cashout-types', 'CashoutTypeController@massDestroy')->name('cashout-types.mass_destroy');

         //app version resource
        Route::post('appversions/switchUpdate', 'AppVersionController@switchUpdate')->name('appversions.switchUpdate');
        Route::resource('/appversions', 'AppVersionController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
// });

//Route::redirect('/', 'dashboard');
Route::get('/', function(){ echo "user";});
Route::group(['as' => 'user.', 'namespace' => 'User'], function () {
    Route::get('/login', );
});

app/Models/Keyword.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Keyword extends Model
{
    use SoftDeletes;
    protected $table = 'keyword';

    protected $fillable = [
        'keyword',
    ];

    public function keyword_type_name()
    {
        return $this->hasOne('App\Models\KeywordLanguage', 'keyword_id', 'id')->Where('language_id', getCurrentLanguage());
    }
    public function multiple_keyword_type_name()
    {
        return $this->hasMany('App\Models\KeywordLanguage', 'keyword_id', 'id');
    }
}

app/Http/Controllers/Admin/KeywordController.php
<?php

namespace App\Http\Controllers\Admin;


use Illuminate\Http\Request;
use DB;
use App\Models\Keyword;
use App\Models\KeywordLanguage;
use App\Models\Language;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreKeywordRequest;
use App\Http\Requests\Admin\UpdateKeywordRequest;
use App\Models\LabelUpdateCheck;
use App\Models\DeviceInfo;

class KeywordController extends Controller
{
    public function index()
    {
        $keywords = Keyword::with(['multiple_keyword_type_name'])->latest()->get();
        return view('admin.keyword.index', compact('keywords'));
    }

    public function create()
    {
        return view('admin.keyword.create');
    }

    public function store(StoreKeywordRequest $request)
    {
        DB::beginTransaction();
        try {
            if (Keyword::where('keyword', $request->keyword)->first()) {
                return redirect()->back()->with('error', trans('validation.custom.already_exist', ['entity' => 'keyword']));
            } else {
                $keyword = Keyword::create($request->only('keyword'));
                if ($keyword) {
                    foreach (getAllLanguages() as $key => $language) {
                        $keywordLanguage = new KeywordLanguage();
                        $keywordLanguage->keyword_language = $request['language_' . $language->code];
                        $keywordLanguage->keyword_id = $keyword->id;
                        $keywordLanguage->language_id = $language->id;
                        $keywordLanguage->save();
                    }
                } else {
                    return redirect()->back()->with('error', trans('validation.attributes.error'));
                }
            }

            $labelUpdateObj = DeviceInfo::where('label_update',1)->update(['label_update' => 0]);
            DB::commit();

            return redirect()->route('admin.keyword.index')->with('message', trans('message.keyword.create'));
        } catch (\Exception $e) {
            DB::rollback();
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    public function edit(Keyword $keyword)
    {
        $languages = Language::all();

        $keywordLanguage = KeywordLanguage::where('keyword_id', $keyword->id)->get();

        return view('admin.keyword.edit', compact('keyword', 'languages', 'keywordLanguage'));
    }

    public function update(UpdateKeywordRequest $request, Keyword $keyword)
    {
        $keywordLanguageDelete = DB::table('keyword_language')->where('keyword_id', $keyword->id)->delete();

        $keyword = Keyword::find($keyword->id);
        $keyword->keyword = $request->keyword;
        $keyword->save();
        if ($keyword) {
            foreach (getAllLanguages() as $key => $language) {
                $lang = $request['language_' . $language->code];
                if ($lang) {
                    $keywordLanguage = new KeywordLanguage();
                    $keywordLanguage->keyword_language = $lang;
                    $keywordLanguage->keyword_id = $keyword->id;
                    $keywordLanguage->language_id = $language->id;
                    $keywordLanguage->save();
                }
            }
        }
        $labelUpdateObj = DeviceInfo::where('label_update',1)->update(['label_update' => 0]);
        return redirect()->route('admin.keyword.index')->with('message', trans('message.keyword.update'));
    }


    public function destroy(Keyword $keyword)
    {
        KeywordLanguage::where('keyword_id', $keyword->id)->delete();
        $keyword->delete();
        return redirect()->back()->with('message', trans('message.keyword.delete'));
    }
}

resources/views/admin/keyword/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                {{ trans('global.create') }}
                {{ trans('cruds.label.title') }}
            </div>

            <div class="card-body">
                <form action="{{ route('admin.keyword.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="keyword">{{ trans('global.keyword.fields.keyword') }}*</label>
                        <input type="text" id="keyword" name="keyword" class="form-control" value="{{ old('keyword', isset($keyword) ? $keyword->keyword : '') }}" />
                        @if ($errors->has('keyword'))
                        <div class="error">
                            {{ $errors->first('keyword') }}
                        </div>
                        @endif
                    </div>
                    @foreach(getAllLanguages() as $key=>$language)
                    <div class="form-group">
                        <label>{{ $language->name }} @if(empty($key)) * @endif</label>
                        <input type="text" name="language_{{ $language->code }}" class="form-control">

                        @if ($errors->has('language_'.$language->code))
                        <div class="error">
                            {{ $errors->first('language_'.$language->code) }}
                        </div>
                        @endif
                    </div>
                    @endforeach
                    <div>
                        <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/keyword/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                {{ trans('global.edit') }}
                {{ trans('cruds.label.title') }}
            </div>

            <div class="card-body">
                <form action="{{ route('admin.keyword.update', [$keyword->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group ">
                        <label for="keyword">{{ trans('global.keyword.fields.keyword') }}*</label>
                        <input type="text" id="keyword" name="keyword" class="form-control" value="{{ old('keyword', isset($keyword) ? $keyword->keyword : '') }}"  readonly="" />
                        @if($errors->has('keyword'))
                        <p class="help-block">
                            {{ $errors->first('keyword') }}
                        </p>
                        @endif
                        <p class="helper-block">
                            {{ trans('global.keyword.fields.keyword_helper') }}
                        </p>
                    </div>
                    @foreach(getAllLanguages() as $key=>$language)
                    <div class="form-group ">
                        <label for="name">{{ $language->name }}@if(empty($key)) * @endif</label>
                        <?php
                        $valuesLang = '';
                        foreach ($keywordLanguage as $keywordLang) {
                            if ($language->id == $keywordLang->language_id) {
                                $valuesLang = $keywordLang->keyword_language;
                            }
                        }
                        ?>
                        <input type="text" id="language" name="language_{{ $language->code }}" class="form-control" value="{{ $valuesLang }}" />
                        @if ($errors->has('language_'.$language->code))
                        <div class="error">
                            {{ $errors->first('language_'.$language->code) }}
                        </div>
                        @endif
                    </div>
                    @endforeach
                    <div>
                        <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/keyword/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-6">
                    
                        {{ trans('cruds.label.title') }} {{ trans('global.list') }}
                    </div>
                    <div class="col-lg-6 text-right">
                        <a class="btn btn-primary" href="{{ route('admin.keywords.create') }}">
                            {{ trans('global.add') }}
                            {{ trans('cruds.label.title') }}
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                        <thead>
                            <tr>
                                <th width="10">
                                    {{ trans('lanKey.uploaded_statement.no') }}
                                </th>
                                <th>
                                    {{ trans('global.keyword.fields.keyword') }}
                                </th>
                                @foreach(getAllLanguages() as $key => $language)
                                <th>
                                    {{ ucfirst($language->name) }}
                                </th>
                                @endforeach
                                <th>
                                    {{ trans('global.actions') }}
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($keywords as $key => $keyword)
                            <tr data-entry-id="{{ $keyword->id }}">
                                <td>
                                    {{ $key+1 }}
                                </td>
                                <td>
                                    {{ $keyword->keyword ?? '' }}
                                </td>
                                @foreach(getAllLanguages() as $key1 => $language)
                                <td>
                                    {{ isset($keyword->multiple_keyword_type_name[$key1]) ? $keyword->multiple_keyword_type_name[$key1]->keyword_language : '' }}
                                </td>
                                @endforeach
                                <td>
                                    <a href="{{ route('admin.keyword.edit', $keyword->id) }}" class="btn btn-sm btn-primary" title="{{ trans('global.edit_icon_title') }}"><i class="fa fa-edit"></i></a>

                                    <form action="{{ route('admin.keyword.destroy', $keyword->id) }}" method="POST"  style="display: none;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <!-- <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}"> -->
                                        <button type="submit" class="btn btn-danger btn-sm deleteSubmit" title="{{ trans('global.delete_icon_title') }}"><i class="fa fa-trash-alt"></i></button>
                                    </form>
                                    <button type="button" class="btn btn-danger btn-sm deleteButton" title="{{ trans('global.delete') }}"><i class="fa fa-trash-alt"></i></button>
                                </td>

                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
        $(function() {
           
           $('body').on('click', '.deleteButton', function() {
                var current = $(this);
                Swal.fire({
                    icon: 'warning',
                    title: "Are you sure delete this?",
                    text: "You won't be able to revert this!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Yes, delete it!",
                }).then((result) => {
                    if (result.value) {
                        current.parent().find('.deleteSubmit').click();
                    }
                });
            });
        });
    </script>
@endsection

resources/views/admin/keyword/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.product.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.product.fields.name') }}
                    </th>
                    <td>
                        {{ $product->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.product.fields.description') }}
                    </th>
                    <td>
                        {!! $product->description !!}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.product.fields.price') }}
                    </th>
                    <td>
                        ${{ $product->price }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection