routes/admin.php
        Route::post('users/document/save', 'UserController@usersDocumentSave')->name('users.document.save');
        Route::get('users/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('users.document.verify');
        Route::post('users/document/verify/save', 'UserController@usersDocumentVerifySave')->name('users.document.verify.save');


        Route::get('users/order/show/{id?}', 'UserController@usersOrderShow')->name('users.order.show');
        Route::get('vendors/order/show/{id?}', 'UserController@vendorsOrderShow')->name('vendors.order.show');
        Route::get('drivers/order/show/{id?}', 'UserController@driversOrderShow')->name('drivers.order.show');


        //Vendor Type resource
        Route::post('vendors/switchUpdate', 'VendorController@switchUpdate')->name('vendors.switchUpdate');
        Route::resource('vendors', 'VendorController');
        Route::delete('vendors_mass_destroy', 'VendorController@massDestroy')->name('vendors.mass_destroy');
        Route::post('vendorProduct/onOff', 'VendorController@productOnOff')->name('vendors.product.onOff');
        Route::post('vendors/document/view', 'UserController@usersDocumentView')->name('vendors.document.view');
        Route::post('vendors/document/save', 'UserController@usersDocumentSave')->name('vendors.document.save');
        Route::get('vendors/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('vendors.document.verify');
        Route::post('vendors/document/verify/save', 'UserController@usersDocumentVerifySave')->name('vendors.document.verify.save');
        Route::post('vendors/product/status', 'VendorController@productStatus')->name('vendors.product.status');


        //Driver Type resource
        Route::post('drivers/switchUpdate', 'DriverController@switchUpdate')->name('drivers.switchUpdate');
        Route::resource('drivers', 'DriverController');
        Route::delete('drivers_mass_destroy', 'DriverController@massDestroy')->name('drivers.mass_destroy');
        Route::post('drivers/document/view', 'UserController@usersDocumentView')->name('drivers.document.view');
        Route::post('drivers/document/save', 'UserController@usersDocumentSave')->name('drivers.document.save');
        Route::get('drivers/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('drivers.document.verify');
        Route::post('drivers/document/verify/save', 'UserController@usersDocumentVerifySave')->name('drivers.document.verify.save');

        //Keyword resource
        Route::post('keyword/keywordUpdate', 'KeywordController@switchUpdate')->name('keyword.switchUpdate');
        Route::resource('keyword', 'KeywordController');
        Route::delete('keyword', 'KeywordController@massDestroy')->name('keyword.mass_destroy');

        //Keyword resource
        Route::post('keywords/switchUpdate', 'KeywordController@switchUpdate')->name('keywords.switchUpdate');
        Route::resource('keywords', 'KeywordController');
        Route::delete('keywords', 'KeywordController@massDestroy')->name('keywords.mass_destroy');

        //Category Type resource
        Route::post('categories/switchUpdate', 'CategoryController@switchUpdate')->name('categories.switchUpdate');
        Route::resource('categories', 'CategoryController');
        Route::delete('categories_mass_destroy', 'CategoryController@massDestroy')->name('categories.mass_destroy');

        //Service Type resource
        Route::post('services/switchUpdate', 'ServiceTypeController@switchUpdate')->name('services.switchUpdate');
        Route::resource('services', 'ServiceTypeController');
        Route::delete('services_mass_destroy', 'ServiceTypeController@massDestroy')->name('services.mass_destroy');

        //Business Type resource
        Route::post('businesses/switchUpdate', 'BusinessTypeController@switchUpdate')->name('businesses.switchUpdate');
        Route::resource('businesses', 'BusinessTypeController');
        Route::delete('businesses_mass_destroy', 'BusinessTypeController@massDestroy')->name('businesses.mass_destroy');

        //Unit Type resource
        Route::post('units/switchUpdate', 'UnitTypeController@switchUpdate')->name('units.switchUpdate');
        Route::resource('units', 'UnitTypeController');
        Route::delete('units_mass_destroy', 'UnitTypeController@massDestroy')->name('units.mass_destroy');

        //Order Status resource
        Route::post('orderStatuses/switchUpdate', 'OrderStatusController@switchUpdate')->name('orderStatuses.switchUpdate');
        Route::resource('orderStatuses', 'OrderStatusController');
        Route::delete('orderStatuses_mass_destroy', 'OrderStatusController@massDestroy')->name('orderStatuses.mass_destroy');

        Route::resource('settings', 'SettingController');

        //Vehicle Type resource
        Route::post('vehicletypes/switchUpdate', 'VehicleTypeController@switchUpdate')->name('vehicletypes.switchUpdate');
        Route::resource('vehicletypes', 'VehicleTypeController');
        Route::delete('vehicletypes_mass_destroy', 'VehicleTypeController@massDestroy')->name('vehicletypes.mass_destroy');

        //Vehicle Color resource
        Route::post('vehiclecolors/switchUpdate', 'VehicleColorController@switchUpdate')->name('vehiclecolors.switchUpdate');
        Route::resource('vehiclecolors', 'VehicleColorController');
        Route::delete('vehiclecolors_mass_destroy', 'VehicleColorController@massDestroy')->name('vehiclecolors.mass_destroy');

        //promocodes resource
        Route::post('promocodes/switchUpdate', 'PromocodeController@switchUpdate')->name('promocodes.switchUpdate');
        Route::resource('promocodes', 'PromocodeController');
        Route::delete('promocodes_mass_destroy', 'PromocodeController@massDestroy')->name('promocodes.mass_destroy');

        //promotions resource
        Route::post('promotions/switchUpdate', 'PromotionController@switchUpdate')->name('promotions.switchUpdate');
        Route::resource('promotions', 'PromotionController');
        Route::delete('promotions_mass_destroy', 'PromotionController@massDestroy')->name('promotions.mass_destroy');

        //promotions resource
        Route::post('contents/switchUpdate', 'ContentController@switchUpdate')->name('content.switchUpdate');
        Route::resource('/content', 'ContentController');
        Route::delete('contents', 'ContentController@massDestroy')->name('content.mass_destroy');

        //promotions resource
        Route::post('cashoutrequest/switchUpdate', 'CashoutRequestController@switchUpdate')->name('cashoutrequest.switchUpdate');
        Route::resource('/cashoutrequest', 'CashoutRequestController');
        Route::delete('cashoutrequest', 'CashoutRequestController@massDestroy')->name('cashoutrequest.mass_destroy');

        //document resource
        Route::post('documents/switchUpdate', 'DocumentsController@switchUpdate')->name('documents.switchUpdate');
        Route::resource('/documents', 'DocumentsController');
        Route::delete('documents', 'DocumentsController@massDestroy')->name('documents.mass_destroy');

        //cbd and cannabis resource
        Route::post('cbdcannabistates/switchUpdate', 'CbdCannabiStateController@switchUpdate')->name('cbdcannabistates.switchUpdate');
        Route::resource('/cbdcannabistates', 'CbdCannabiStateController');
        Route::delete('cbdcannabistates', 'CbdCannabiStateController@massDestroy')->name('cbdcannabistates.mass_destroy');


        //currency
        Route::post('currencys/switchUpdate', 'CurrencysController@switchUpdate')->name('currencys.switchUpdate');
        Route::resource('/currencys', 'CurrencysController');
        Route::delete('currencys', 'CurrencysController@massDestroy')->name('currencys.mass_destroy');

        Route::get('orders/{status?}', 'UserController@Allorders')->name('orders');
        Route::post('orders/change/status', 'UserController@adminOrderChangeStatus')->name('order.change.status');
        Route::post('orders/change/reverse/entry', 'UserController@adminOrderReverseEntry')->name('order.change.reverse.entry');
    
        //strain effects resource
        Route::post('strain-effects/switchUpdate', 'StrainEffectController@switchUpdate')->name('strain-effects.switchUpdate');
        Route::resource('/strain-effects', 'StrainEffectController');
        Route::delete('strain-effects', 'StrainEffectController@massDestroy')->name('strain-effects.mass_destroy');

         //strain effects resource
         Route::post('cashout-types/switchUpdate', 'CashoutTypeController@switchUpdate')->name('cashout-types.switchUpdate');
         Route::resource('/cashout-types', 'CashoutTypeController');
         Route::delete('cashout-types', 'CashoutTypeController@massDestroy')->name('cashout-types.mass_destroy');

         //app version resource
        Route::post('appversions/switchUpdate', 'AppVersionController@switchUpdate')->name('appversions.switchUpdate');
        Route::resource('/appversions', 'AppVersionController');
        Route::delete('appversions', 'AppVersionController@massDestroy')->name('appversions.mass_destroy');


         //strain effects resource
         Route::post('inventorys/switchUpdate', 'InventoryController@switchUpdate')->name('inventorys.switchUpdate');
         Route::resource('/inventorys', 'InventoryController');
         Route::delete('inventorys', 'InventoryController@massDestroy')->name('inventorys.mass_destroy');

         //Brand Type resource
        Route::post('brands/switchUpdate', 'BrandController@switchUpdate')->name('brands.switchUpdate');
        Route::resource('brands', 'BrandController');
        Route::delete('brands_mass_destroy', 'BrandController@massDestroy')->name('brands.mass_destroy');


    });

    Route::group(['middleware' => ['auth', 'marketing'], 'as' => 'admin.', 'namespace' => 'Admin'], function () {
        Route::redirect('/', 'admin/marketing/dashboard');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
// });

//Route::redirect('/', 'dashboard');
Route::get('/', function(){ echo "user";});
Route::group(['as' => 'user.', 'namespace' => 'User'], function () {
    Route::get('/login', );
});

app/Http/Controllers/Admin/VehicleTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\VehicleType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreUnitTypeRequest;
use App\Http\Requests\Admin\UpdateUnitTypeRequest;
use App\Models\LabelCodeDyanamic;
use DB;

class VehicleTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $vehicleTypes = VehicleType::with('multiple_vehicle_type_name')->latest()->get();
            return view('admin.vehicle-types.index', compact('vehicleTypes'));
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('admin.vehicle-types.create');
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUnitTypeRequest $request)
    {
        DB::beginTransaction();
        try {
            $input = $request->all();
            $temp['name'] = 'txt_vehicle_type_name_title';
            $temp = VehicleType::create($temp);
            $name = $temp['name'] . '_' . $temp->id;

            foreach (getAllLanguages() as $key => $language) {
                $label_code_array = ["name" => $name];
                foreach ($label_code_array as $key => $value) {
                    $where_arr = ['code' => $value, 'language_id' => $language->id];
                    $insert_arr = ['value' => $input[$language->name][$key]];
                    LabelCodeDyanamic::updateOrCreate($where_arr, $insert_arr);
                }
            }

            $where = ['name' => $name];
            VehicleType::where('id', $temp->id)->update($where);
            DB::commit();
            return redirect()->route('admin.vehicletypes.index')->with('message', trans('api.add', ['entity' => 'vehicle type']));
        } catch (\Exception $e) {
            DB::rollback();
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UnitType  $unit
     * @return \Illuminate\Http\Response
     */
    public function show(VehicleType $unit)
    {
        try {
            return view('admin.vehicle-types.show', compact('unit'));
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\VehicleType  $vehicletype
     * @return \Illuminate\Http\Response
     */
    public function edit(VehicleType $vehicletype)
    {
        try {
            return view('admin.vehicle-types.edit', compact('vehicletype'));
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\VehicleType  $vehicletype
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUnitTypeRequest $request, VehicleType $vehicletype)
    {

        DB::beginTransaction();
        try {
            $input = $request->all();
            $name = $vehicletype->name;

            foreach (getAllLanguages() as $key => $language) {
                $label_code_array = ["name" => $name];
                foreach ($label_code_array as $key => $value) {
                    $where_arr = ['code' => $value, 'language_id' => $language->id];
                    $insert_arr = ['value' => $input[$language->name][$key]];
                    LabelCodeDyanamic::updateOrCreate($where_arr, $insert_arr);
                }
            }

            DB::commit();
            return redirect()->route('admin.vehicletypes.index')->with('message', trans('api.update', ['entity' => 'vehicle type']));
        } catch (\Exception $e) {
            DB::rollback();
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UnitType  $unit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        DB::beginTransaction();
        try {
            $data = VehicleType::find(request('ids'));
            $data->multiple_vehicle_type_name()->delete();
            $data->delete();
            DB::commit();
            return response()->noContent();
        } catch (\Exception $e) {
            DB::rollback();
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    public function massDestroy(Request $request)
    {
        DB::beginTransaction();
        try {
            $ids = request('ids');
            foreach ($ids as $key => $id) {
                $unit = VehicleType::find(request('ids'));
                $unit->multiple_vehicle_type_name()->delete();
            }
            VehicleType::whereIn('id', $ids)->delete();
            DB::commit();
            return response()->noContent();
        } catch (\Exception $e) {
            DB::rollback();
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    public function switchUpdate(Request $request)
    {
        try {
            $unit = VehicleType::find($request->ids);
            if (empty($unit->is_active)) {
                $unit->is_active = 1;
            } else {
                $unit->is_active = 0;
            }
            $unit->save();
            return response()->noContent();
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }
}

resources/views/admin/vehicle-types/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                {{ trans('global.create') }} {{ trans('cruds.vehicletype.title_singular') }}
            </div>

            <div class="card-body">
                <form id="add_vehicletype" action="{{ route('admin.vehicletypes.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach(getAllLanguages() as $key => $language)
                        <li class="nav-item">
                            <a class="nav-link {{ (empty($key)) ? 'active' : '' }}" data-toggle="tab" href="#{{ $language->name }}">{{ ucfirst($language->name) }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        @foreach(getAllLanguages() as $key => $language)
                        <div class="tab-pane {{ (empty($key)) ? 'active' : '' }}" id="{{ $language->name }}">
                            <br>
                            <div class="form-group">
                                <label>{{ ucfirst($language->name).' '.trans('cruds.vehicletype.title') }}*</label>
                                <input type="text" name="{{ $language->name }}[name]" class="form-control" value="{{ old($language->name.'.name') }}">
                                @if ($errors->has($language->name . '.name'))
                                <div class="error">
                                    {{ $errors->first($language->name . '.name') }}
                                </div>
                                @endif
                            </div>
                        </div>
                        @endforeach
                    </div>
                    <div class="form-group finalSubmitBtn">
                        <input class="btn btn-danger btn-md" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {

        $('#add_vehicletype').validate({ // initialize the plugin
            rules: {
                name: {
                    required: false,
                }
            },
            submitHandler: function(form) {
                form.submit();
            }
        });

    });
</script>
@endsection

resources/views/admin/vehicle-types/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                {{ trans('global.edit') }} {{ trans('cruds.vehicletype.title_singular') }}
            </div>

            <div class="card-body">
                <form id="edit_vehicletype" action="{{ route('admin.vehicletypes.update', [$vehicletype->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach(getAllLanguages() as $key => $language)
                        <li class="nav-item">
                            <a class="nav-link {{ (empty($key)) ? 'active' : '' }}" data-toggle="tab" href="#{{ $language->name }}">{{ ucfirst($language->name) }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        @foreach(getAllLanguages() as $key => $language)
                        <div id="{{ $language->name }}" class="tab-pane {{ (empty($key)) ? 'active' : '' }}">
                            <br>
                            <div class="form-group">
                                <label>{{ ucfirst($language->name).' '.trans('cruds.unit.fields.name') }}*</label>
                                <input type="text" name="{{ $language->name }}[name]" class="form-control" value="{{ old($language->name.'.name', isset($vehicletype->multiple_vehicle_type_name[$key]) ? $vehicletype->multiple_vehicle_type_name[$key]->value : '') }}">
                                @if ($errors->has($language->name . '.name'))
                                <div class="error">
                                    {{ $errors->first($language->name . '.name') }}
                                </div>
                                @endif
                            </div>
                        </div>
                        @endforeach
                    </div>
                    <div>
                        <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {

        $('#edit_vehicletype').validate({ // initialize the plugin
            rules: {
                name: {
                    required: false,
                },
            },
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'name'])",
                },
            },
            submitHandler: function(form) {
                form.submit();
            }
        });

    });
</script>
@endsection

resources/views/admin/vehicle-types/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-6">
                        {{ trans('cruds.vehicletype.title') }} {{ trans('global.list') }}
                    </div>
                    <div class="col-lg-6 text-right">
                        <a class="btn btn-primary" href="{{ route('admin.vehicletypes.create') }}">
                            {{ trans('global.add') }} {{ trans('cruds.vehicletype.title_singular') }}
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                        <thead>
                            <tr>
                                <th>{{ trans('global.no') }}</th>
                                @foreach(getAllLanguages() as $key => $language)
                                <th>
                                    {{ trans('cruds.vehicletype.title').' - '.ucfirst($language->name) }}
                                </th>
                                @endforeach
                                <th>{{ trans('global.status') }}</th>
                                <th>{{ trans('global.actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($vehicleTypes as $key => $vehicleType)
                            <tr data-entry-id="{{ $vehicleType->id }}">
                                <td>{{ $key+1 }}</td>
                                @foreach(getAllLanguages() as $key1 => $language)
                                <td>{{ $vehicleType->multiple_vehicle_type_name ? $vehicleType->multiple_vehicle_type_name[$key1]->value : '' }}</td>
                                @endforeach
                                <td>@include('partials.switch', ['id'=> $vehicleType->id,'is_active'=>$vehicleType->is_active] )</td>
                                <td>@include('partials.actions', ['id' => $vehicleType->id])</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vehicle-types/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-3 text-right">
                <a class="btn btn-primary" href="{{ route('admin.units.index') }}">
                    {{ trans('global.back_to_list') }} {{ trans('cruds.unit.title') }}
                </a>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                {{ trans('global.show') }} {{ trans('cruds.unit.title') }}
            </div>

            <div class="card-body">
                <div class="mb-2">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <th>
                                    {{ trans('cruds.unit.fields.id') }}
                                </th>
                                <td>
                                    {{ $unit->id }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('cruds.unit.fields.name') }}
                                </th>
                                <td>
                                    {{ ucfirst($unit->name) }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection