routes/admin.php
        Route::post('users/document/save', 'UserController@usersDocumentSave')->name('users.document.save');
        Route::get('users/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('users.document.verify');
        Route::post('users/document/verify/save', 'UserController@usersDocumentVerifySave')->name('users.document.verify.save');


        Route::get('users/order/show/{id?}', 'UserController@usersOrderShow')->name('users.order.show');
        Route::get('vendors/order/show/{id?}', 'UserController@vendorsOrderShow')->name('vendors.order.show');
        Route::get('drivers/order/show/{id?}', 'UserController@driversOrderShow')->name('drivers.order.show');


        //Vendor Type resource
        Route::post('vendors/switchUpdate', 'VendorController@switchUpdate')->name('vendors.switchUpdate');
        Route::resource('vendors', 'VendorController');
        Route::delete('vendors_mass_destroy', 'VendorController@massDestroy')->name('vendors.mass_destroy');
        Route::post('vendorProduct/onOff', 'VendorController@productOnOff')->name('vendors.product.onOff');
        Route::post('vendors/document/view', 'UserController@usersDocumentView')->name('vendors.document.view');
        Route::post('vendors/document/save', 'UserController@usersDocumentSave')->name('vendors.document.save');
        Route::get('vendors/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('vendors.document.verify');
        Route::post('vendors/document/verify/save', 'UserController@usersDocumentVerifySave')->name('vendors.document.verify.save');
        Route::post('vendors/product/status', 'VendorController@productStatus')->name('vendors.product.status');


        //Driver Type resource
        Route::post('drivers/switchUpdate', 'DriverController@switchUpdate')->name('drivers.switchUpdate');
        Route::resource('drivers', 'DriverController');
        Route::delete('drivers_mass_destroy', 'DriverController@massDestroy')->name('drivers.mass_destroy');
        Route::post('drivers/document/view', 'UserController@usersDocumentView')->name('drivers.document.view');
        Route::post('drivers/document/save', 'UserController@usersDocumentSave')->name('drivers.document.save');
        Route::get('drivers/document/verify/{id?}', 'UserController@usersDocumentVerify')->name('drivers.document.verify');
        Route::post('drivers/document/verify/save', 'UserController@usersDocumentVerifySave')->name('drivers.document.verify.save');

        //Keyword resource
        Route::post('keyword/keywordUpdate', 'KeywordController@switchUpdate')->name('keyword.switchUpdate');
        Route::resource('keyword', 'KeywordController');
        Route::delete('keyword', 'KeywordController@massDestroy')->name('keyword.mass_destroy');

        //Keyword resource
        Route::post('keywords/switchUpdate', 'KeywordController@switchUpdate')->name('keywords.switchUpdate');
        Route::resource('keywords', 'KeywordController');
        Route::delete('keywords', 'KeywordController@massDestroy')->name('keywords.mass_destroy');

        //Category Type resource
        Route::post('categories/switchUpdate', 'CategoryController@switchUpdate')->name('categories.switchUpdate');
        Route::resource('categories', 'CategoryController');
        Route::delete('categories_mass_destroy', 'CategoryController@massDestroy')->name('categories.mass_destroy');

        //Service Type resource
        Route::post('services/switchUpdate', 'ServiceTypeController@switchUpdate')->name('services.switchUpdate');
        Route::resource('services', 'ServiceTypeController');
        Route::delete('services_mass_destroy', 'ServiceTypeController@massDestroy')->name('services.mass_destroy');

        //Business Type resource
        Route::post('businesses/switchUpdate', 'BusinessTypeController@switchUpdate')->name('businesses.switchUpdate');
        Route::resource('businesses', 'BusinessTypeController');
        Route::delete('businesses_mass_destroy', 'BusinessTypeController@massDestroy')->name('businesses.mass_destroy');

        //Unit Type resource
        Route::post('units/switchUpdate', 'UnitTypeController@switchUpdate')->name('units.switchUpdate');
        Route::resource('units', 'UnitTypeController');
        Route::delete('units_mass_destroy', 'UnitTypeController@massDestroy')->name('units.mass_destroy');

        //Order Status resource
        Route::post('orderStatuses/switchUpdate', 'OrderStatusController@switchUpdate')->name('orderStatuses.switchUpdate');
        Route::resource('orderStatuses', 'OrderStatusController');
        Route::delete('orderStatuses_mass_destroy', 'OrderStatusController@massDestroy')->name('orderStatuses.mass_destroy');

        Route::resource('settings', 'SettingController');

        //Vehicle Type resource
        Route::post('vehicletypes/switchUpdate', 'VehicleTypeController@switchUpdate')->name('vehicletypes.switchUpdate');
        Route::resource('vehicletypes', 'VehicleTypeController');
        Route::delete('vehicletypes_mass_destroy', 'VehicleTypeController@massDestroy')->name('vehicletypes.mass_destroy');

        //Vehicle Color resource
        Route::post('vehiclecolors/switchUpdate', 'VehicleColorController@switchUpdate')->name('vehiclecolors.switchUpdate');
        Route::resource('vehiclecolors', 'VehicleColorController');
        Route::delete('vehiclecolors_mass_destroy', 'VehicleColorController@massDestroy')->name('vehiclecolors.mass_destroy');

        //promocodes resource
        Route::post('promocodes/switchUpdate', 'PromocodeController@switchUpdate')->name('promocodes.switchUpdate');
        Route::resource('promocodes', 'PromocodeController');
        Route::delete('promocodes_mass_destroy', 'PromocodeController@massDestroy')->name('promocodes.mass_destroy');

        //promotions resource
        Route::post('promotions/switchUpdate', 'PromotionController@switchUpdate')->name('promotions.switchUpdate');
        Route::resource('promotions', 'PromotionController');
        Route::delete('promotions_mass_destroy', 'PromotionController@massDestroy')->name('promotions.mass_destroy');

        //promotions resource
        Route::post('contents/switchUpdate', 'ContentController@switchUpdate')->name('content.switchUpdate');
        Route::resource('/content', 'ContentController');
        Route::delete('contents', 'ContentController@massDestroy')->name('content.mass_destroy');

        //promotions resource
        Route::post('cashoutrequest/switchUpdate', 'CashoutRequestController@switchUpdate')->name('cashoutrequest.switchUpdate');
        Route::resource('/cashoutrequest', 'CashoutRequestController');
        Route::delete('cashoutrequest', 'CashoutRequestController@massDestroy')->name('cashoutrequest.mass_destroy');

        //document resource
        Route::post('documents/switchUpdate', 'DocumentsController@switchUpdate')->name('documents.switchUpdate');
        Route::resource('/documents', 'DocumentsController');
        Route::delete('documents', 'DocumentsController@massDestroy')->name('documents.mass_destroy');

        //cbd and cannabis resource
        Route::post('cbdcannabistates/switchUpdate', 'CbdCannabiStateController@switchUpdate')->name('cbdcannabistates.switchUpdate');
        Route::resource('/cbdcannabistates', 'CbdCannabiStateController');
        Route::delete('cbdcannabistates', 'CbdCannabiStateController@massDestroy')->name('cbdcannabistates.mass_destroy');


        //currency
        Route::post('currencys/switchUpdate', 'CurrencysController@switchUpdate')->name('currencys.switchUpdate');
        Route::resource('/currencys', 'CurrencysController');
        Route::delete('currencys', 'CurrencysController@massDestroy')->name('currencys.mass_destroy');

        Route::get('orders/{status?}', 'UserController@Allorders')->name('orders');
        Route::post('orders/change/status', 'UserController@adminOrderChangeStatus')->name('order.change.status');
        Route::post('orders/change/reverse/entry', 'UserController@adminOrderReverseEntry')->name('order.change.reverse.entry');
    
        //strain effects resource
        Route::post('strain-effects/switchUpdate', 'StrainEffectController@switchUpdate')->name('strain-effects.switchUpdate');
        Route::resource('/strain-effects', 'StrainEffectController');
        Route::delete('strain-effects', 'StrainEffectController@massDestroy')->name('strain-effects.mass_destroy');

         //strain effects resource
         Route::post('cashout-types/switchUpdate', 'CashoutTypeController@switchUpdate')->name('cashout-types.switchUpdate');
         Route::resource('/cashout-types', 'CashoutTypeController');
         Route::delete('cashout-types', 'CashoutTypeController@massDestroy')->name('cashout-types.mass_destroy');

         //app version resource
        Route::post('appversions/switchUpdate', 'AppVersionController@switchUpdate')->name('appversions.switchUpdate');
        Route::resource('/appversions', 'AppVersionController');
        Route::delete('appversions', 'AppVersionController@massDestroy')->name('appversions.mass_destroy');


         //strain effects resource
         Route::post('inventorys/switchUpdate', 'InventoryController@switchUpdate')->name('inventorys.switchUpdate');
         Route::resource('/inventorys', 'InventoryController');
         Route::delete('inventorys', 'InventoryController@massDestroy')->name('inventorys.mass_destroy');

         //Brand Type resource
        Route::post('brands/switchUpdate', 'BrandController@switchUpdate')->name('brands.switchUpdate');
        Route::resource('brands', 'BrandController');
        Route::delete('brands_mass_destroy', 'BrandController@massDestroy')->name('brands.mass_destroy');


    });

    Route::group(['middleware' => ['auth', 'marketing'], 'as' => 'admin.', 'namespace' => 'Admin'], function () {
        Route::redirect('/', 'admin/marketing/dashboard');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
// });

//Route::redirect('/', 'dashboard');
Route::get('/', function(){ echo "user";});
Route::group(['as' => 'user.', 'namespace' => 'User'], function () {
    Route::get('/login', );
});

app/Models/AppVersion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AppVersion extends Model
{
    protected $guarded = [];
    protected $table = 'app_versions';
}

app/Http/Controllers/Admin/AppVersionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AppVersion;
use Illuminate\Http\Request;

class AppVersionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $appversions = AppVersion::orderBy('id','desc')->get();
            return view('admin.appversions.index', compact('appversions'));
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AppVersion  $appVersion
     * @return \Illuminate\Http\Response
     */
    public function show(AppVersion $appVersion)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AppVersion  $appVersion
     * @return \Illuminate\Http\Response
     */
    public function edit(AppVersion $appversion)
    {
        try {
            return view('admin.appversions.edit', compact('appversion'));
        } catch (\Exception $e) {
            throw new \App\Exceptions\CustomException($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AppVersion  $appVersion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AppVersion $appversion)
    {
        $appversion->version = $request->version;
        $appversion->is_forcefully = $request->is_forcefully;
        $appversion->save();
        return redirect()->route('admin.appversions.index')->with('message', trans('message.appversions.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AppVersion  $appVersion
     * @return \Illuminate\Http\Response
     */
    public function destroy(AppVersion $appVersion)
    {
        //
    }
}

resources/views/admin/appversions/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                {{ trans('global.create') }} {{ trans('cruds.documents.title_singular') }}
            </div>

            <div class="card-body">
                <form id="add_document" action="{{ route('admin.documents.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach(getAllLanguages() as $key => $language)
                        <li class="nav-item">
                            <a class="nav-link {{ (empty($key)) ? 'active' : '' }}" data-toggle="tab" href="#{{ $language->name }}">{{ ucfirst($language->name) }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        @foreach(getAllLanguages() as $key => $language)
                        <div class="tab-pane {{ (empty($key)) ? 'active' : '' }}" id="{{ $language->name }}">
                            <br>
                            <div class="form-group">
                                <label>{{ ucfirst($language->name).' '.trans('cruds.documents.fields.name') }}*</label>
                                <input type="text" name="{{ $language->name }}[name]" class="form-control" value="{{ old($language->name.'.name') }}">
                                @if ($errors->has($language->name . '.name'))
                                <div class="error">
                                    {{ $errors->first($language->name . '.name') }}
                                </div>
                                @endif
                            </div>
                            @if(empty($key))
                                <div class="form-group">
                                    <label>{{trans('global.role')}}*</label>
                                    <select class="form-control" name="role_id">
                                        <option value="">Please select role</option>
                                        <option value="2">Vendor</option>
                                        <option value="3">Driver</option>
                                        <option value="4">User</option>
                                    </select>
                                    @if ($errors->has('role_id'))
                                    <div class="error">
                                        {{ $errors->first('role_id') }}
                                    </div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>{{trans('cruds.documents.fields.is_required')}}*</label>
                                    <select class="form-control" name="is_required">
                                       <option value="0">NO</option>
                                        <option value="1">YES</option>
                                    </select>
                                    @if ($errors->has('is_required'))
                                    <div class="error">
                                        {{ $errors->first('is_required') }}
                                    </div>
                                    @endif
                                </div>
                            @endif
                        </div>
                        @endforeach
                    </div>
                    <div class="form-group finalSubmitBtn">
                        <input class="btn btn-danger btn-md" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {

        $('#add_document').validate({ // initialize the plugin
            rules: {
                name: {
                    required: false,
                },
                
            },
            submitHandler: function(form) {
                form.submit();
            }
        });

    });
</script>
@endsection

resources/views/admin/appversions/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                {{ trans('global.edit') }} {{ trans('cruds.appversions.title_singular') }}
            </div>

            <div class="card-body">
                <form id="edit_document" action="{{ route('admin.appversions.update', [$appversion->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="form-group">
                            <input type="text" class="form-control" name="version" value="{{ old('version', isset($appversion->version) ? $appversion->version : '') }}" required="">
                        </div>
                        <div class="form-group">
                            <label>{{trans('cruds.appversions.fields.is_forcefully')}}*</label>
                            <select class="form-control" name="type" disabled>
                                <option value="1" @if($appversion->type == "2") selected  @endif>Android</option>
                                <option value="2" @if($appversion->type == "1") selected  @endif>IOS</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>{{trans('global.role')}}*</label>
                            <select class="form-control" name="role_id" disabled>
                                <option value="2" @if($appversion->role_id == "2") selected  @endif>Vendor</option>
                                <option value="3" @if($appversion->role_id == "3") selected  @endif>Driver</option>
                                <option value="4" @if($appversion->role_id == "4") selected  @endif>User</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>{{trans('cruds.appversions.fields.is_forcefully')}}*</label>
                            <select class="form-control" name="is_forcefully" readonly="">
                                <option value="0" @if($appversion->is_forcefully == "0") selected  @endif>NO</option>
                                <option value="1" @if($appversion->is_forcefully == "1") selected  @endif>YES</option>
                            </select>
                        </div>
                    </div>
                    <div>
                        <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {

        $('#edit_document').validate({ // initialize the plugin
            rules: {
                name: {
                    required: false,
                },
            },
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'name'])",
                },
            },
            submitHandler: function(form) {
                form.submit();
            }
        });

    });
</script>
@endsection

resources/views/admin/appversions/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        @include("partials.alert")
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-6">
                        {{ trans('cruds.appversions.title') }} {{ trans('global.list') }}
                    </div>
                    <div class="col-lg-6 text-right">
                        {{-- <a class="btn btn-primary" href="{{ route('admin.appversions.create') }}">
                            {{ trans('global.add') }} {{ trans('cruds.appversions.title_singular') }}
                        </a> --}}
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                        <thead>
                            <tr>
                                <th>{{ trans('global.no') }}</th>
                                <th>{{ trans('cruds.appversions.fields.version') }}</th>
                                <th>{{ trans('cruds.appversions.fields.type') }}</th>
                                <th>{{ trans('cruds.appversions.fields.role_id') }}</th>
                                <th>{{ trans('cruds.appversions.fields.is_forcefully') }}</th>
                                {{-- <th>{{ trans('global.status') }}</th> --}}
                                <th>{{ trans('global.actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($appversions as $key => $appversion)
                            <tr data-entry-id="{{ $appversion->id }}">
                                <td>{{ $key+1 }}</td>
                                <td>{{ $appversion->version }}</td>
                                <td>
                                    @if($appversion->type == 2) 
                                        Android
                                    @elseif($appversion->type == 1) 
                                        IOS
                                    @endif
                                </td>
                                <td>@if($appversion->role_id == 2) 
                                        Vendor
                                    @elseif($appversion->role_id == 3) 
                                        Driver
                                    @elseif($appversion->role_id == 4) 
                                        User     
                                    @endif
                                </td>
                                <td>{{ $appversion->is_forcefully ? 'YES' : 'NO'}}</td>
                                {{-- <td>@include('partials.switch', ['id'=> $appversion->id,'is_active'=>$appversion->is_active] )</td> --}}
                                <td>@include('partials.actions', ['id' => $appversion->id])</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/appversions/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mb-3 text-right">
                <a class="btn btn-primary" href="{{ route('admin.units.index') }}">
                    {{ trans('global.back_to_list') }} {{ trans('cruds.unit.title') }}
                </a>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                {{ trans('global.show') }} {{ trans('cruds.unit.title') }}
            </div>

            <div class="card-body">
                <div class="mb-2">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <th>
                                    {{ trans('cruds.unit.fields.id') }}
                                </th>
                                <td>
                                    {{ $unit->id }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('cruds.unit.fields.name') }}
                                </th>
                                <td>
                                    {{ ucfirst($unit->name) }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection